version: '3.4'

services:

  sitegenerator:
    image: tgartner/site:v1.0.5
    container_name: sitegenerator
    networks:
      - mgm_news_network
    restart: unless-stopped
    #command: [ "sleep", "infinity" ]
    # ports:
    #   - 4000:4000
    volumes:
      - ${DATA_DIR_ON_HOST}/blogs:/site/_posts
      - ${DATA_DIR_ON_HOST}/site:/site/_site

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    #   image: {{ nginx_certbot_image }}
    #   container_name: nginx
    #   restart: unless-stopped
    #   networks:
    #     - mgm_news_network
    #   ports:
    #     - '80:80'
    #     - '443:443'
    #   environment:
    #     CERTBOT_EMAIL: {{ certbot_email }}
    #     SERVER_URL: {{ server_url }}
    #     USE_LOCAL_CA: {{ certbot_use_local_ca }}
    #     DEBUG: {{ certbot_debug }}
    networks:
      - mgm_news_network
    volumes:
      - ${DATA_DIR_ON_HOST}/site:/usr/share/nginx/html:ro
      - ${DATA_DIR_ON_HOST}/logs:/logs
      - ${DATA_DIR_ON_HOST}/site/nginx_secrets:/etc/letsencrypt
      - ${DATA_DIR_ON_HOST}/site/nginx_conf.d:/etc/nginx/user_conf.d

networks:
  mgm_news_network:
    name: mgm_news_network
