version: '3.4'

services:

  linkedin_scraper:
    image: linkedin_scraper
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    container_name: linkedin_scraper
    networks:
      - linkedin_scraper
    restart: unless-stopped
    volumes:
      - ..:/workspace:cached
      - ./data/blogs:/site/_posts
      - ./data/site:/site/_site
      - ./data/commandhistory:/commandhistory
    command: /bin/sh -c "while sleep 1000; do :; done"

  selenium:
    image: selenium
    build:
      dockerfile: Dockerfile-selenium
    container_name: selenium
    shm_size: 2gb
    networks:
      - linkedin_scraper
    restart: unless-stopped
    ports:
      - 4444:4444
      - 7900:7900

networks:
  linkedin_scraper:
    name: linkedin_scraper
